version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rent_any_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-scripts:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata: